"""
StatsFlow Pipeline Generator
-----------------------------
Transforms the cleaning engine's operations log into a downloadable,
fully executable Python/Pandas script.

This ensures total reproducibility and auditability —
a key academic and industrial requirement.
"""

from typing import List, Dict, Any
from datetime import datetime


def generate_pipeline_script(
    filename: str,
    operations: List[Dict[str, Any]],
    missing_strategy: str,
    outlier_strategy: str,
) -> str:
    """
    Generate a complete, runnable Python script that replicates the exact
    cleaning pipeline applied by StatsFlow.

    Args:
        filename: Original uploaded filename.
        operations: Ordered list of cleaning operations from CleaningEngine.
        missing_strategy: The missing value strategy that was used.
        outlier_strategy: The outlier treatment strategy that was used.

    Returns:
        A string containing the full Python script.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Script Header ─────────────────────────────────────────────────────────
    script_parts = [
        f'"""',
        f'StatsFlow — Auto-Generated Data Cleaning Pipeline',
        f'==================================================',
        f'Generated at  : {timestamp}',
        f'Source file   : {filename}',
        f'Missing strategy  : {missing_strategy}',
        f'Outlier strategy  : {outlier_strategy}',
        f'',
        f'This script was automatically generated by StatsFlow.',
        f'It replicates the exact cleaning pipeline applied to your dataset.',
        f'Run with: python cleaning_pipeline.py',
        f'"""',
        f'',
        f'import pandas as pd',
        f'import numpy as np',
    ]

    # Conditionally import KNN imputer
    if missing_strategy == "knn":
        script_parts.append("from sklearn.impute import KNNImputer")

    script_parts += [
        f'',
        f'',
        f'# ── Configuration ────────────────────────────────────────────────────',
        f'INPUT_FILE  = "{filename}"    # Path to your raw dataset',
        f'OUTPUT_FILE = "cleaned_dataset.csv"  # Where to save the cleaned data',
        f'',
        f'',
        f'def load_data(filepath: str) -> pd.DataFrame:',
        f'    """Load the dataset from CSV or Excel."""',
        f'    if filepath.endswith(".csv"):',
        f'        return pd.read_csv(filepath)',
        f'    elif filepath.endswith((".xlsx", ".xls")):',
        f'        return pd.read_excel(filepath)',
        f'    else:',
        f'        raise ValueError(f"Unsupported file type: {{filepath}}")',
        f'',
        f'',
    ]

    # ── Generate per-operation functions ──────────────────────────────────────
    for op in operations:
        operation = op.get("operation", "")
        script_parts += _generate_operation_code(operation, op)

    # ── Main Pipeline Function ────────────────────────────────────────────────
    script_parts += [
        f'',
        f'def run_pipeline() -> pd.DataFrame:',
        f'    """Execute the full cleaning pipeline step by step."""',
        f'    print("=" * 60)',
        f'    print("  StatsFlow Data Cleaning Pipeline")',
        f'    print("=" * 60)',
        f'',
        f'    # Load raw data',
        f'    print(f"\\n[1/5] Loading data from: {{INPUT_FILE}}")',
        f'    df = load_data(INPUT_FILE)',
        f'    print(f"      Raw shape: {{df.shape[0]}} rows × {{df.shape[1]}} columns")',
        f'',
        f'    # Step 2: Remove duplicates',
        f'    print("\\n[2/5] Removing duplicate rows...")',
        f'    df = remove_duplicates(df)',
        f'',
        f'    # Step 3: Drop high-null columns',
        f'    print("\\n[3/5] Dropping high-null columns (>80% missing)...")',
        f'    df = drop_high_null_columns(df, threshold=0.80)',
        f'',
        f'    # Step 4: Impute missing values',
        f'    print(f"\\n[4/5] Imputing missing values (strategy: {missing_strategy})...")',
        f'    df = impute_missing_values(df)',
        f'',
        f'    # Step 5: Treat outliers',
        f'    print(f"\\n[5/5] Treating outliers (strategy: {outlier_strategy})...")',
        f'    df = treat_outliers(df)',
        f'',
        f'    # Finalize',
        f'    df.reset_index(drop=True, inplace=True)',
        f'    print(f"\\n✅ Cleaning complete!")',
        f'    print(f"   Final shape: {{df.shape[0]}} rows × {{df.shape[1]}} columns")',
        f'',
        f'    # Export cleaned data',
        f'    df.to_csv(OUTPUT_FILE, index=False)',
        f'    print(f"   Saved to: {{OUTPUT_FILE}}")',
        f'    print("=" * 60)',
        f'',
        f'    return df',
        f'',
        f'',
        f'if __name__ == "__main__":',
        f'    cleaned_df = run_pipeline()',
    ]

    return "\n".join(script_parts)


def _generate_operation_code(operation: str, op_data: Dict) -> List[str]:
    """
    Generate the Python function code block for a specific cleaning operation.

    Args:
        operation: Operation identifier string.
        op_data: Full operation dict from the cleaning log.

    Returns:
        List of code lines for this operation's function definition.
    """
    lines = []

    if operation == "remove_duplicates":
        lines = [
            "def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:",
            '    """Remove fully duplicate rows from the DataFrame."""',
            "    before = len(df)",
            "    df = df.drop_duplicates()",
            "    removed = before - len(df)",
            "    print(f'      Removed {removed} duplicate rows')",
            "    return df",
            "",
        ]

    elif operation == "drop_high_null_columns":
        cols = op_data.get("columns_affected", [])
        lines = [
            "def drop_high_null_columns(df: pd.DataFrame, threshold: float = 0.80) -> pd.DataFrame:",
            '    """Drop columns where the null ratio exceeds the threshold."""',
            "    null_ratio = df.isnull().mean()",
            "    cols_to_drop = null_ratio[null_ratio > threshold].index.tolist()",
            "    df = df.drop(columns=cols_to_drop)",
            f"    print(f'      Dropped columns: {{cols_to_drop}}')",
            "    return df",
            "",
        ]

    elif "impute" in operation:
        strategy = operation.replace("impute_", "")
        lines = _generate_imputation_function(strategy)

    elif "outlier" in operation and "none" not in operation:
        strategy = operation.replace("outlier_", "")
        lines = _generate_outlier_function(strategy)

    elif operation == "outlier_none":
        lines = [
            "def treat_outliers(df: pd.DataFrame) -> pd.DataFrame:",
            '    """Outlier treatment skipped by user configuration."""',
            "    print('      Skipped (strategy=none)')",
            "    return df",
            "",
        ]

    elif operation == "reset_index":
        lines = []  # Handled inline in run_pipeline()

    return ["    " + line if line and not line.startswith("def ") and not line.startswith('"""') else line for line in lines]


def _generate_imputation_function(strategy: str) -> List[str]:
    """Generate the impute_missing_values function for the given strategy."""
    header = [
        f"def impute_missing_values(df: pd.DataFrame) -> pd.DataFrame:",
        f'    """Impute missing values using the \'{strategy}\' strategy."""',
        f"    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()",
        f"    categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()",
        f"",
    ]

    if strategy == "knn":
        body = [
            f"    # KNN Imputation for numeric columns",
            f"    if numeric_cols:",
            f"        imputer = KNNImputer(n_neighbors=5)",
            f"        df[numeric_cols] = imputer.fit_transform(df[numeric_cols])",
        ]
    elif strategy == "mean":
        body = [
            f"    for col in numeric_cols:",
            f"        if df[col].isnull().any():",
            f"            df[col].fillna(df[col].mean(), inplace=True)",
        ]
    elif strategy == "median":
        body = [
            f"    for col in numeric_cols:",
            f"        if df[col].isnull().any():",
            f"            df[col].fillna(df[col].median(), inplace=True)",
        ]
    else:  # mode
        body = [
            f"    for col in numeric_cols:",
            f"        if df[col].isnull().any():",
            f"            df[col].fillna(df[col].mode()[0], inplace=True)",
        ]

    categorical = [
        f"",
        f"    # Categorical columns — always fill with mode",
        f"    for col in categorical_cols:",
        f"        if df[col].isnull().any():",
        f"            mode_val = df[col].mode()",
        f"            df[col].fillna(mode_val[0] if not mode_val.empty else 'Unknown', inplace=True)",
        f"",
        f"    missing_remaining = int(df.isnull().sum().sum())",
        f"    print(f'      Missing values remaining: {{missing_remaining}}')",
        f"    return df",
        f"",
    ]

    return header + body + categorical


def _generate_outlier_function(strategy: str) -> List[str]:
    """Generate the treat_outliers function for the given strategy."""
    header = [
        f"def treat_outliers(df: pd.DataFrame) -> pd.DataFrame:",
        f'    """Treat outliers in numeric columns using the \'{strategy}\' method."""',
        f"    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()",
        f"    total_treated = 0",
        f"",
    ]

    if strategy == "zscore":
        body = [
            f"    for col in numeric_cols:",
            f"        col_data = df[col].dropna()",
            f"        if len(col_data) < 4 or col_data.std() == 0:",
            f"            continue",
            f"        z_scores = (df[col] - col_data.mean()) / col_data.std()",
            f"        outlier_mask = z_scores.abs() > 3",
            f"        count = int(outlier_mask.sum())",
            f"        if count > 0:",
            f"            df.loc[outlier_mask, col] = col_data.median()",
            f"            total_treated += count",
        ]
    elif strategy == "iqr":
        body = [
            f"    for col in numeric_cols:",
            f"        col_data = df[col].dropna()",
            f"        if len(col_data) < 4:",
            f"            continue",
            f"        q1, q3 = col_data.quantile(0.25), col_data.quantile(0.75)",
            f"        iqr = q3 - q1",
            f"        if iqr == 0:",
            f"            continue",
            f"        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr",
            f"        count = int(((df[col] < lower) | (df[col] > upper)).sum())",
            f"        if count > 0:",
            f"            df[col] = df[col].clip(lower=lower, upper=upper)",
            f"            total_treated += count",
        ]
    else:
        body = ["    pass"]

    footer = [
        f"",
        f"    print(f'      Total outlier cells treated: {{total_treated}}')",
        f"    return df",
        f"",
    ]

    return header + body + footer